FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Como estamos dentro da pasta ChatCI, podemos usar diretamente
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante do código fonte
COPY . .

# Expor a porta
EXPOSE 5000

# Iniciar o servidor
CMD ["python", "app.py"]